[package]
name = "rtree"
version = "0.0.0"
description = "tree but in rust"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

[dependencies]
clap = "4.4.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"